# AU template: https://github.com/majkinetor/au-packages-template

version: '{build}'
max_jobs: 1
image: Visual Studio 2022
# History plugin requires complete log
#clone_depth: 5
branches:
  only:
  - master
#build:
#  verbosity: minimal

environment:
  # Set au version to use or omit to use the latest. Specify branch name to use development version from Github
  au_version:
  au_push: true
  # Force test: use 1 to test all, or N to split testing into N groups
  au_test_groups: 1

  # GitHub releases
  CYF_RELEASE_TOKEN:
    secure: OrV8sBUF3drDVJsllYml4XEk94VMCA6B0weklM+CJVhJuPOfgZmi1ODKTl9JDO/N6XDcpRwC+4GXMWk2+GVPnU0Q+H3Kj1qUAUrnkVSh4UpYIQEKvQ58tNh/mObCl3ZE # https://ci.appveyor.com/tools/encrypt
  FR_RELEASE_TOKEN:
    secure: OrV8sBUF3drDVJsllYml4bj4c7r2uCDXKrI7IU31Jg1EUGbtS0aGxVXvhfEnn+oj7xFDf1KJp8GJfxGbrx+U1JSVwUjLw8J7ZkePCtzgyNs45y8qk9ZlITiMTRF7+8vB # https://ci.appveyor.com/tools/encrypt
  PG_RELEASE_TOKEN:
    secure: OrV8sBUF3drDVJsllYml4R97RKm9vDQ1fFbXDlCea6BEcLeJmO/Y0DamF9sghmd8X8lVgaebct2DrJTLBltXHkNMQQuqx3u/LkFiZTAGvjyO36J3q+3hMYSqgxMNXZqO # https://ci.appveyor.com/tools/encrypt

  # Github token to commit pushed packages to repository
  github_user_repo: kjxbyz/chocolatey-packages
  github_api_key:
    secure: OrV8sBUF3drDVJsllYml4fdTfTDHofA+wlQ0UVENaPkQwp/YFv9rs/YCcW36H3yPvtRJJb9kLbwu4DmKOTtzGUc/Y+Qmq5eu9PLYLIYqfcHnJdqsGZrx7kCW258evO5d # https://ci.appveyor.com/tools/encrypt


  # Mail credentials - for error notifications
  mail_user:
    secure: YOUR_EMAIL_ACCOUNT_HERE_ENCRYPTED_STRING # https://ci.appveyor.com/tools/encrypt
  mail_pass:
    secure: YOUR_EMAIL_PASSWORD_HERE_ENCRYPTED_STRING # https://ci.appveyor.com/tools/encrypt
  mail_server: smtp.sendgrid.net
  mail_port: 465
  mail_enablessl: true

  # ID of the gist used to save run results - create a gist under the github_user (secret or not) and grab the id - https://gist.github.com/name/id
  # Optional, leave empty to create anonymous gist
  gist_id: 6e62e5cab8fb28487b265620bd85755d

  # Force test: gist id for test results
  gist_id_test: 8baabce7b41e0dab6ef5763ece3d2e20

  # Chocolatey API key - to push updated packages
  api_key:
    secure: 3HL0ADelr9OmnVMdGQ5V6DPQ3poQ6CI+X19cnu6zXeM6f7eaiL0IATEgPPuHTHhk # https://ci.appveyor.com/tools/encrypt

init:
- git config --global user.email "kjxbyz888@outlook.com"
- git config --global user.name "kjxbyz"
- git config --global core.safecrlf false

install:
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable
- git --version
- ps: |
    git clone -q https://github.com/majkinetor/au.git $Env:TEMP/au
    . "$Env:TEMP/au/scripts/Install-AU.ps1" $Env:au_version

- ps: |
    "Build info"
    '  {0,-20} {1}' -f 'SCHEDULED BUILD:', ($Env:APPVEYOR_SCHEDULED_BUILD -eq 'true')
    '  {0,-20} {1}' -f 'FORCED BUILD:'   , ($Env:APPVEYOR_FORCED_BUILD    -eq 'true')
    '  {0,-20} {1}' -f 'RE BUILD:'       , ($Env:APPVEYOR_RE_BUILD        -eq 'true')

build_script:
- ps: |
    $ErrorActionPreference = 'Continue'

    if ($Env:APPVEYOR_PROJECT_NAME  -like '*test*') { ./test_all.ps1 "random $Env:au_test_groups"; return }

    if ( ($Env:APPVEYOR_SCHEDULED_BUILD -ne 'true') -and ($Env:APPVEYOR_FORCED_BUILD -ne 'true') ) {
        switch -regex ($Env:APPVEYOR_REPO_COMMIT_MESSAGE)
        {
            '\[AU (.+?)\]'   { $forced = $Matches[1] }

            '\[PUSH (.+?)\]' {
                $packages = $Matches[1] -split ' '
                Write-Host "PUSHING PACKAGES: $packages"
                foreach ($package in $packages) {
                    Write-Host ("{0}`n{1}`n" -f ('-'*60), "PACKAGE: $package")
                    $package_dir = ls -recurse | ? { $_.Name -eq "$package.nuspec"} | select -First 1 | % Directory
                    if (!$package_dir) { Write-Warning "Can't find package '$package'"; continue }
                    pushd $package_dir; choco pack; Push-Package; popd
                }
                return
            }
        }
    }

    ./update_all.ps1 -ForcedPackages $forced
    7z a au_temp.zip $Env:TEMP\chocolatey\au\*

artifacts:
- path: update_info.xml
- path: Update-AUPackages.md
- path: au_temp.zip

notifications:
- provider: Email
  to: $(mail_user)
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
