version: '{build}'
max_jobs: 1
image: Visual Studio 2022
# History plugin requires complete log
#clone_depth: 5
branches:
  only:
  - master
#build:
#  verbosity: minimal

environment:
  # Set au version to use or omit to use the latest. Specify branch name to use development version from Github
  au_version: 1.0.0
  au_push: true
  # Force test: use 1 to test all, or N to split testing into N groups
  au_test_groups: 1

  # GitHub releases
  ATY_RELEASE_TOKEN:
    secure: OrV8sBUF3drDVJsllYml4fYnqGl0euu2fW6rH7R4MvwVYkjeJ0e0Pcld4TB2N364dMnTXa0Vjj3F8V7qJW0CqRMRgr9ODVSgpGq4xMMnmSuKg4wVHjABvamUcwlpjYQa # https://ci.appveyor.com/tools/encrypt
  FR_RELEASE_TOKEN:
    secure: OrV8sBUF3drDVJsllYml4TWMpmH3Ch75Yld2jpZCVAnsybUt+bLo8ddkQZp8VGszd+BAOmbKNW90F7oSZjo8M6LTsv8qg7PV/CZ114/Nq7JmUODKuUD8zPLF+Xbvu/PA # https://ci.appveyor.com/tools/encrypt
  PG_RELEASE_TOKEN:
    secure: OrV8sBUF3drDVJsllYml4XJR+dbMbv/YLL5xlMaTrGssuwXhFacKCDbKDDXp7z0Br/kq36yKYr0bFUxjV/VBOJU7bS2wue2AGJnnDjOpiOBQcNLKELI36wD+BPLT9TbX # https://ci.appveyor.com/tools/encrypt
  KTY_RELEASE_TOKEN:
    secure: OrV8sBUF3drDVJsllYml4XDXcxzvWfqMVkdLLLJxjBgJ2UywhU18CmwSwlLl5Z/xqF7TbmQkkRxcV9cccpwQEtkMQk1VlpnMk8SHVzw+11+Ok33tVoFgme88v9ajMFoU # https://ci.appveyor.com/tools/encrypt
  YXE_RELEASE_TOKEN:
    secure: OrV8sBUF3drDVJsllYml4VI7HRQGnkRNTIWvVAoKTH67sb/hVk4l/Bb/2W+d9XjKOidEHc7WPNrCj/t4+GdJj2CZegQ1yjOfX+eqp4TGmCvqo3jt2BHfluARo1KYqrb6 # https://ci.appveyor.com/tools/encrypt
  CONN_RELEASE_TOKEN:
    secure: OrV8sBUF3drDVJsllYml4cZTa572f3/Q/DsbnK3x8Boecicx8Evl/VK85pzoZCSyHBcx0TvOkgFiAtsMsxn+pB/5F/VdDykbBI7XX3uZJUoLFg3IXihwXxT8RXb+fDx2 # https://ci.appveyor.com/tools/encrypt

  # Github token to commit pushed packages to repository
  github_user_repo: insco-inc/chocolatey-packages
  github_api_key:
    secure: dY2fUH/wE/TRLFv0pOpEUjvFsw/1xSaQuXREn7l6Je9swYgqJ6kA/Sw78WDsDxT4 # https://ci.appveyor.com/tools/encrypt

  # Mail credentials - for error notifications
  mail_user:
    secure: 9ezq0373BNdInG8KOYNHU/9Z4vwomu6flzhHDZQ7/QQ= # https://ci.appveyor.com/tools/encrypt
#  mail_pass:
#    secure: YOUR_EMAIL_PASSWORD_HERE_ENCRYPTED_STRING # https://ci.appveyor.com/tools/encrypt
#  mail_server: smtp.sendgrid.net
#  mail_port: 465
  mail_enablessl: true

  # ID of the gist used to save run results - create a gist under the github_user (secret or not) and grab the id - https://gist.github.com/name/id
  # Optional, leave empty to create anonymous gist
  gist_id: 6e62e5cab8fb28487b265620bd85755d

  # Force test: gist id for test results
  gist_id_test: 8baabce7b41e0dab6ef5763ece3d2e20

  # Chocolatey API key - to push updated packages
  api_key:
    secure: 3HL0ADelr9OmnVMdGQ5V6DPQ3poQ6CI+X19cnu6zXeM6f7eaiL0IATEgPPuHTHhk # https://ci.appveyor.com/tools/encrypt

  #Chocolatey version we want to use when checking for updates (usually latest).
  choco_version: '2.2.2'
  nupkg_cache_path: C:\packages

init:
- git config --global user.email "kjxbyz888@outlook.com"
- git config --global user.name "kjxbyz"
- git config --global core.safecrlf false

install:
- ps: |
    $chocoVersion = $Env:choco_version
    if (!(Test-Path "$env:nupkg_cache_path")) { mkdir -Force "$env:nupkg_cache_path" }
    @{
      'chocolatey' = $chocoVersion
       # Uncomment and input the version if you are using any of these in AU scripts
       #      'wormies-au-helpers' = 'VERSION_HERE'
       #      'chocolatey-core.extension' = 'VERSION_HERE'
       #      'autohotkey.install' = 'VERSION_HERE'
    }.GetEnumerator() | % {
      if (!(Test-Path "${env:nupkg_cache_path}\$($_.Key).$($_.Value).nupkg")) { rm "${env:nupkg_cache_path}\$($_.Key).*.nupkg" ; iwr "https://chocolatey.org/api/v2/package/$($_.Key)/$($_.Value)" -OutFile "${env:nupkg_cache_path}\$($_.Key).$($_.Value).nupkg" }
      if ($_.Key -eq 'chocolatey') { choco upgrade $_.Key --version $_.Value --source ${env:nupkg_cache_path} --allow-downgrade --pre }
      else { choco install $_.Key --version $_.Value --source ${env:nupkg_cache_path} --ignore-dependencies }
    }
    rm "$env:ChocolateyInstall\logs\*.log"
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable
- git --version
- choco --version
- ps: |
    choco install chocolatey-au --version $Env:au_version -y

- ps: |
    "Build info"
    '  {0,-20} {1}' -f 'SCHEDULED BUILD:', ($Env:APPVEYOR_SCHEDULED_BUILD -eq 'true')
    '  {0,-20} {1}' -f 'FORCED BUILD:'   , ($Env:APPVEYOR_FORCED_BUILD    -eq 'true')
    '  {0,-20} {1}' -f 'RE BUILD:'       , ($Env:APPVEYOR_RE_BUILD        -eq 'true')

build_script:
- ps: |
    $ErrorActionPreference = 'Continue'

    if ($Env:APPVEYOR_PROJECT_NAME  -like '*test*') { ./test_all.ps1 "random $Env:au_test_groups"; return }

    if ( ($Env:APPVEYOR_SCHEDULED_BUILD -ne 'true') -and ($Env:APPVEYOR_FORCED_BUILD -ne 'true') ) {
        switch -regex ($Env:APPVEYOR_REPO_COMMIT_MESSAGE)
        {
            '\[AU (.+?)\]'   { $forced = $Matches[1] }

            '\[PUSH (.+?)\]' {
                $packages = $Matches[1] -split ' '
                Write-Host "PUSHING PACKAGES: $packages"
                foreach ($package in $packages) {
                    Write-Host ("{0}`n{1}`n" -f ('-'*60), "PACKAGE: $package")
                    $package_dir = ls -recurse | ? { $_.Name -eq "$package.nuspec"} | select -First 1 | % Directory
                    if (!$package_dir) { Write-Warning "Can't find package '$package'"; continue }
                    try {
                      pushd $package_dir
                      if (Test-Path update.ps1 -ea 0) { ./update.ps1 }
                      choco pack
                      Push-Package
                    } finally {
                      popd
                    }
                }
                return
            }
        }
    }

    ./update_all.ps1 -ForcedPackages $forced
    7z a au_temp.zip $Env:TEMP\chocolatey\au\*

artifacts:
- path: update_info.xml
- path: Update-AUPackages.md
- path: au_temp.zip

notifications:
- provider: Email
  to: $(mail_user)
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

cache:
  - '%nupkg_cache_path% -> .appveyor.yml'

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
